extern NSString * const kZORNCoreDataStackErrorDomain;

static const NSInteger kZORNCoreDataStackStackAlreadyBuiltErrorCode = 1001;
extern NSString * const kZORNCoreDataStackStackAlreadyBuiltErrorLocalizedDescription;
extern NSString * const kZORNCoreDataStackStackAlreadyBuiltErrorRecoverySuggestion;